---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: canonical-ubuntu-12.04
    driver_config:
      box: 'canonical-ubuntu-12.04'
      box_url: 'http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box'
      customize:
        memory: 2048
        cpus: 2
suites:
  - name: default
    run_list:
      - recipe[kafka_broker::default]
    attributes:
